const templateConfigs = {
  classicOrnate: {
    accent: "#172554",
    background: "linear-gradient(135deg, #fffaf0 0%, #ffffff 48%, #f8fafc 100%)",
    badgeBg: "#e0e7ff",
    badgeText: "#172554",
    borderColor: "#172554",
    decoration: "ornate",
    headingFont: "font-serif",
    innerClass: "",
    panelBg: "rgba(255, 255, 255, 0.86)",
    kicker: "Formal Recognition",
    lineColor: "#172554",
    nameColor: "#172554",
    nameFont: "font-serif",
    outerClass: "bg-white",
    sealColor: "#172554",
    sealLabel: "Official Seal",
    secondary: "#c59f36",
    soft: "#eef2ff"
  },
  modernWave: {
    accent: "#0f766e",
    background: "linear-gradient(135deg, #ffffff 0%, #f0fdfa 56%, #ffffff 100%)",
    badgeBg: "#ccfbf1",
    badgeText: "#115e59",
    borderColor: "#14b8a6",
    decoration: "wave",
    headingFont: "",
    innerClass: "",
    panelBg: "rgba(255, 255, 255, 0.76)",
    kicker: "Professional Certificate",
    lineColor: "#d6a84f",
    nameColor: "#0f766e",
    nameFont: "",
    outerClass: "bg-white",
    sealColor: "#d97706",
    sealLabel: "Official Seal",
    secondary: "#d97706",
    soft: "#ccfbf1"
  },
  vintageBorder: {
    accent: "#52525b",
    background: "repeating-linear-gradient(45deg, rgba(120, 113, 108, 0.045) 0 2px, transparent 2px 8px), linear-gradient(135deg, #f8f1df 0%, #fffaf0 52%, #ece7da 100%)",
    badgeBg: "#e7e5e4",
    badgeText: "#44403c",
    borderColor: "#78716c",
    decoration: "ornate",
    headingFont: "font-serif",
    innerClass: "",
    panelBg: "rgba(255, 250, 240, 0.86)",
    kicker: "Certificate of Merit",
    lineColor: "#a8a29e",
    nameColor: "#44403c",
    nameFont: "font-serif",
    outerClass: "",
    sealColor: "#78716c",
    sealLabel: "Official Seal",
    secondary: "#a8a29e",
    soft: "#f5f5f4"
  },
  goldCorner: {
    accent: "#b7791f",
    background: "linear-gradient(135deg, #ffffff 0%, #fffbeb 50%, #ffffff 100%)",
    badgeBg: "#fef3c7",
    badgeText: "#92400e",
    borderColor: "#172554",
    decoration: "ornate",
    headingFont: "font-serif",
    innerClass: "",
    panelBg: "rgba(255, 255, 255, 0.88)",
    kicker: "Achievement Award",
    lineColor: "#d6a84f",
    nameColor: "#92400e",
    nameFont: "font-serif",
    outerClass: "",
    sealColor: "#d6a84f",
    sealLabel: "Gold Seal",
    secondary: "#172554",
    soft: "#fef3c7"
  },
  darkLuxury: {
    accent: "#f7d774",
    background: "radial-gradient(circle at 20% 10%, rgba(247, 215, 116, 0.16), transparent 28%), linear-gradient(135deg, #111111 0%, #1f2937 55%, #09090b 100%)",
    badgeBg: "rgba(247, 215, 116, 0.14)",
    badgeText: "#fde68a",
    borderColor: "#f7d774",
    dark: true,
    decoration: "wave",
    headingFont: "font-serif",
    innerClass: "",
    panelBg: "rgba(0, 0, 0, 0.18)",
    kicker: "Premium Recognition",
    lineColor: "#f7d774",
    nameColor: "#fde68a",
    nameFont: "font-serif",
    outerClass: "",
    sealColor: "#f7d774",
    sealLabel: "Official Seal",
    secondary: "#a16207",
    soft: "#fde68a"
  },
  floralCreative: {
    accent: "#0f766e",
    background: "linear-gradient(135deg, #ffffff 0%, #fff7ed 54%, #ecfeff 100%)",
    badgeBg: "#ffedd5",
    badgeText: "#9a3412",
    borderColor: "#0f766e",
    decoration: "floral",
    headingFont: "font-serif",
    innerClass: "",
    panelBg: "rgba(255, 255, 255, 0.8)",
    kicker: "Creative Recognition",
    lineColor: "#f97316",
    nameColor: "#0f766e",
    nameFont: "font-serif",
    outerClass: "",
    sealColor: "#f97316",
    sealLabel: "Official Seal",
    secondary: "#f97316",
    soft: "#ccfbf1"
  },
  playfulAward: {
    accent: "#ea580c",
    background: "linear-gradient(135deg, #fff7ed 0%, #ffffff 56%, #fef3c7 100%)",
    badgeBg: "#fed7aa",
    badgeText: "#9a3412",
    borderColor: "#fb923c",
    decoration: "playful",
    headingFont: "",
    innerClass: "",
    panelBg: "rgba(255, 255, 255, 0.76)",
    kicker: "Award Certificate",
    lineColor: "#0ea5e9",
    nameColor: "#c2410c",
    nameFont: "",
    outerClass: "",
    sealColor: "#ea580c",
    sealLabel: "Award Badge",
    secondary: "#0ea5e9",
    soft: "#ffedd5"
  },
  blueCorporate: {
    accent: "#1d4ed8",
    background: "linear-gradient(135deg, #eff6ff 0%, #ffffff 48%, #dbeafe 100%)",
    badgeBg: "#dbeafe",
    badgeText: "#1e3a8a",
    borderColor: "#2563eb",
    decoration: "wave",
    headingFont: "",
    innerClass: "",
    panelBg: "rgba(255, 255, 255, 0.82)",
    kicker: "Corporate Certificate",
    lineColor: "#2563eb",
    nameColor: "#1d4ed8",
    nameFont: "",
    outerClass: "",
    sealColor: "#1d4ed8",
    sealLabel: "Official Seal",
    secondary: "#38bdf8",
    soft: "#dbeafe"
  },
  minimalElegant: {
    accent: "#334155",
    background: "#ffffff",
    badgeBg: "#f1f5f9",
    badgeText: "#334155",
    borderColor: "#cbd5e1",
    decoration: null,
    headingFont: "font-serif tracking-[0.16em]",
    innerClass: "",
    panelBg: "#ffffff",
    kicker: "Distinguished Certificate",
    lineColor: "#94a3b8",
    nameColor: "#0f172a",
    nameFont: "font-serif",
    outerClass: "",
    sealColor: "#64748b",
    sealLabel: "Official Seal",
    secondary: "#64748b",
    soft: "#f8fafc"
  },
  academicSeal: {
    accent: "#1e3a8a",
    background: "linear-gradient(135deg, #ffffff 0%, #f8fafc 58%, #eff6ff 100%)",
    badgeBg: "#dbeafe",
    badgeText: "#1e3a8a",
    borderColor: "#1e3a8a",
    decoration: "academic",
    headingFont: "font-serif",
    innerClass: "",
    panelBg: "rgba(255, 255, 255, 0.86)",
    kicker: "Academic Honor",
    lineColor: "#1e3a8a",
    nameColor: "#1e3a8a",
    nameFont: "font-serif",
    outerClass: "",
    sealColor: "#1e3a8a",
    sealLabel: "Academic Seal",
    secondary: "#d6a84f",
    soft: "#dbeafe"
  }
};

export default templateConfigs;
